global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'aiapp-dev'
    environment: 'development'

rule_files:
  - "rules/*.yml"
  - "alerts/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Kubernetes API Server
  - job_name: 'kubernetes-apiservers'
    kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
            - default
    scheme: https
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecure_skip_verify: true
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    relabel_configs:
      - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
        action: keep
        regex: default;kubernetes;https

  # Kubernetes Nodes
  - job_name: 'kubernetes-nodes'
    kubernetes_sd_configs:
      - role: node
    scheme: https
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecure_skip_verify: true
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)

  # Kubernetes Pods
  - job_name: 'kubernetes-pods'
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: kubernetes_pod_name

  # API Gateway
  - job_name: 'api-gateway'
    kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
            - dev-gateway-ns
    relabel_configs:
      - source_labels: [__meta_kubernetes_service_name]
        action: keep
        regex: api-gateway
      - source_labels: [__meta_kubernetes_endpoint_port_name]
        action: keep
        regex: management
    metrics_path: /actuator/prometheus
    scrape_interval: 10s

  # Auth Service
  - job_name: 'auth-service'
    kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
            - dev-auth-ns
    relabel_configs:
      - source_labels: [__meta_kubernetes_service_name]
        action: keep
        regex: auth-service
      - source_labels: [__meta_kubernetes_endpoint_port_name]
        action: keep
        regex: management
    metrics_path: /actuator/prometheus
    scrape_interval: 10s

  # Payment Service
  - job_name: 'payment-service'
    kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
            - dev-payment-ns
    relabel_configs:
      - source_labels: [__meta_kubernetes_service_name]
        action: keep
        regex: payment-service
      - source_labels: [__meta_kubernetes_endpoint_port_name]
        action: keep
        regex: management
    metrics_path: /actuator/prometheus
    scrape_interval: 10s

  # AI Content Service
  - job_name: 'ai-content-service'
    kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
            - dev-ai-content-ns
    relabel_configs:
      - source_labels: [__meta_kubernetes_service_name]
        action: keep
        regex: ai-content-service
      - source_labels: [__meta_kubernetes_endpoint_port_name]
        action: keep
        regex: management
    metrics_path: /actuator/prometheus
    scrape_interval: 10s

  # Notification Service
  - job_name: 'notification-service'
    kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
            - dev-notification-ns
    relabel_configs:
      - source_labels: [__meta_kubernetes_service_name]
        action: keep
        regex: notification-service
      - source_labels: [__meta_kubernetes_endpoint_port_name]
        action: keep
        regex: management
    metrics_path: /actuator/prometheus
    scrape_interval: 10s

  # Analytics Service
  - job_name: 'analytics-service'
    kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
            - dev-analytics-ns
    relabel_configs:
      - source_labels: [__meta_kubernetes_service_name]
        action: keep
        regex: analytics-service
      - source_labels: [__meta_kubernetes_endpoint_port_name]
        action: keep
        regex: management
    metrics_path: /actuator/prometheus
    scrape_interval: 10s

  # Kafka Exporter
  - job_name: 'kafka-exporter'
    static_configs:
      - targets: ['kafka-exporter:9308']
    scrape_interval: 30s

  # Redis Exporter
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # PostgreSQL Exporter
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s